#USER
api.users.register:
    path: /users/register
    controller: App\Controller\UserController::register
    methods: POST

api.users.get:
    path: /users
    controller: App\Controller\UserController:getUsers
    methods: GET

api.users.confirm:
    path: /users/confirm/{token}
    controller: App\Controller\UserController:confirm
    methods: GET

api.users.get_by_id:
    path: /users/{id}
    controller: App\Controller\UserController:getUserById
    methods: GET
    requirements:
        id: '\d+'

#TASTING ROOM
api.tastingroom.create:
    path: /tasting-rooms
    controller: App\Controller\TastingRoomController:create
    methods: POST

api.tastingroom.delete:
    path: /tasting-rooms/{tastingRoom}
    controller: App\Controller\TastingRoomController:delete
    methods: DELETE
    requirements:
        tastingRoomId: '\d+'

api.tastingroom.join:
    path: /tasting-rooms/join
    controller: App\Controller\TastingRoomController:join
    methods: POST

api.tastingroom.start:
    path: /tasting-rooms
    controller: App\Controller\TastingRoomController:start
    methods: PUT

api.tastingroom.get:
    path: /tasting-rooms
    controller: App\Controller\TastingRoomController:list
    methods: GET

api.tastingroom.get_by_id:
    path: /tasting-rooms/{id}
    controller: App\Controller\TastingRoomController:getDetailsById
    methods: GET
    requirements:
        tastingRoom: '\d+'

#BEER
api.beer.get:
    path: /beers/tasting-rooms/{tastingRoomId}
    controller: App\Controller\BeerController:listBeersForTastingRoom
    methods: GET
    requirements:
        tastingRoomId: '\d+'

api.beer.add_tastingroom:
    path: /beers/tasting-rooms
    controller: App\Controller\BeerController:addBeerToTastingRoom
    methods: POST

#REVIEW
api.review.create:
    path: /reviews
    controller: App\Controller\ReviewController:create
    methods: POST

api.review.statistic:
    path: /reviews/statistics
    controller: App\Controller\ReviewController:statistics
    methods: GET

api.review.statistic_by_tastingroom:
    path: /reviews/statistics/{tastingRoomId}
    controller: App\Controller\ReviewController:statisticsByTastingRoom
    methods: GET

#QUESTIONS AND ANSWERS
api.questions_answers.get:
    path: /questions/answers
    controller: App\Controller\QuestionAnswerController:getQuestionsAndAnswers
    methods: GET