#USER
api.users.register:
    path: /users/register
    controller: App\Controller\UserController::register
    methods: POST

api.users.get:
    path: /users
    controller: App\Controller\UserController:getUsers
    methods: GET

#TASTING ROOM
api.tastingroom.create:
    path: /tasting-rooms
    controller: App\Controller\TastingRoomController:create
    methods: POST

api.tastingroom.delete:
    path: /tasting-rooms/{tastingRoom}
    controller: App\Controller\TastingRoomController:delete
    methods: DELETE
    requirements:
        tastingRoomId: '\d+'

api.tastingroom.join:
    path: /tasting-rooms/join
    controller: App\Controller\TastingRoomController:join
    methods: POST

#BEER
api.beer.create:
    path: /beers
    controller: App\Controller\BeerController:create
    methods: POST

api.beer.get:
    path: /beers
    controller: App\Controller\BeerController:list
    methods: GET

api.beer.add_tastingroom:
    path: /beers/tasting-rooms
    controller: App\Controller\BeerController:addBeerToTastingRoom
    methods: POST