openapi: 3.0.0
info:
  title: GrudlannApp
  version: '1'
paths:
  /api/users/login:
    post:
      tags:
        - User
      summary: Login
      operationId: 'App\Controller\AbstractBaseController::docLogin'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                email:
                  type: string
                  uniqueItems: true
                password:
                  type: string
                  example: Testowe123!
              type: object
  /api/users/register:
    post:
      tags:
        - User
      summary: Registration
      operationId: 'App\Controller\UserController::register'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                email:
                  type: string
                  uniqueItems: true
                nick:
                  type: string
                  uniqueItems: true
                password:
                  type: string
                  example: Testowe123!
              type: object
